In [2]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

def labelencoder(df,Columns):
    #df = pd.read_csv("artifacts/data.csv")

    for col in Columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))

    return df

In [3]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Machine Learning\Dataset\airlines_flights_data.csv")

In [4]:
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

# Data_clean & Save

In [5]:
df.flight.value_counts()

flight
UK-706     3235
UK-772     2741
UK-720     2650
UK-836     2542
UK-822     2468
           ...
SG-9923       1
6E-6474       1
6E-865        1
G8-705        1
G8-107        1
Name: count, Length: 1561, dtype: int64

In [6]:
df['flight'] = df.flight.str.split('-').str[0]
df.flight = df.flight.replace({'6.00E':'6E','0.00E+00':'6E'})

In [7]:
df.flight.value_counts()

flight
UK    127859
AI     80892
6E     43120
G8     23173
I5     16098
SG      9011
Name: count, dtype: int64

In [8]:
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [9]:
df['departure_time'] = np.where(df['departure_time'] == 'Early_Morning', 'Morning',
                              np.where(df['departure_time'] == 'Afternoon', 'Evening',
                              np.where(df['departure_time'] == 'Late_Night', 'Night',
                                       df['departure_time'])))

df['arrival_time'] = df['arrival_time'].replace({
    'Early_Morning':'Morning',
    'Afternoon':'Evening',
    'Late_Night':'Night'
})

df['duration_hours'] = df['duration'].astype(int)
df['duration_minutes'] = ((df['duration'] - df['duration_hours']) * 60).round().astype(int)

df.drop(['duration','index'],axis=1,inplace=True)

In [10]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price,duration_hours,duration_minutes
0,SpiceJet,SG,Delhi,Evening,zero,Night,Mumbai,Economy,1,5953,2,10
1,SpiceJet,SG,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5953,2,20
2,AirAsia,I5,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5956,2,10
3,Vistara,UK,Delhi,Morning,zero,Evening,Mumbai,Economy,1,5955,2,15
4,Vistara,UK,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5955,2,20

In [11]:
df.to_csv("Flight_clean.csv", index=False)

In [12]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price,duration_hours,duration_minutes
0,SpiceJet,SG,Delhi,Evening,zero,Night,Mumbai,Economy,1,5953,2,10
1,SpiceJet,SG,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5953,2,20
2,AirAsia,I5,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5956,2,10
3,Vistara,UK,Delhi,Morning,zero,Evening,Mumbai,Economy,1,5955,2,15
4,Vistara,UK,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5955,2,20

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   days_left         300153 non-null  int64
 9   price             300153 non-null  int64
 10  duration_hours    300153 non-null  int64
 11  duration_minutes  300153 non-null  int64
dtypes: int64(4), object(8)
memory usage: 27.5+ MB

In [14]:
df.to_csv("Flight_clean.csv", index=False)

## All Categorical_Columns LabelEnoden

In [15]:
#label = ['airline','flight','source_city','departure_time','stops','arrival_time','destination_city','class']
label = df.select_dtypes(include='object')


data = labelencoder(df,label)
data

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price,duration_hours,duration_minutes
0,4,4,2,0,2,2,5,1,1,5953,2,10
1,4,4,2,1,2,1,5,1,1,5953,2,20
2,0,3,2,1,2,1,5,1,1,5956,2,10
3,5,5,2,1,2,0,5,1,1,5955,2,15
4,5,5,2,1,2,1,5,1,1,5955,2,20
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,5,5,1,1,0,0,3,0,49,69265,10,5
300149,5,5,1,0,0,2,3,0,49,77105,10,25
300150,5,5,1,1,0,2,3,0,49,79099,13,50
300151,5,5,1,1,0,0,3,0,49,81585,10,0
300152,5,5,1,1,0,0,3,0,49,81585,10,5

In [16]:
x = data.drop('price',axis=1)
y = data.price

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)

(240122, 11)
(60031, 11)
(240122,)

In [18]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(xtrain,ytrain)
print(rf.score(xtest,ytest))

0.9846017824317045

## Select Importance Features

In [92]:
from sklearn.feature_selection import SelectFromModel

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x, y)

selector = SelectFromModel(rf, threshold=0.01, prefit=True)
X_selected = selector.transform(x)


selected_features = x.columns[selector.get_support()]
print("Selected Features:", selected_features)

importances = rf.feature_importances_
feature_names = x.columns

feat_importances = pd.Series(importances, index=feature_names)
feat_importances = feat_importances.sort_values(ascending=False)
print(feat_importances)

c:\Users\tanvi\miniconda3\envs\env\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(

Selected Features: Index(['source_city', 'class', 'duration', 'days_left'], dtype='object')
class               0.880106
duration            0.059514
days_left           0.018657
source_city         0.010748
destination_city    0.009534
flight              0.005539
airline             0.005263
arrival_time        0.004557
departure_time      0.004229
stops               0.001853
dtype: float64

In [93]:
X_selected

array([[ 2.  ,  1.  ,  2.17,  1.  ],
       [ 2.  ,  1.  ,  2.33,  1.  ],
       [ 2.  ,  1.  ,  2.17,  1.  ],
       ...,
       [ 1.  ,  0.  , 13.83, 49.  ],
       [ 1.  ,  0.  , 10.  , 49.  ],
       [ 1.  ,  0.  , 10.08, 49.  ]], shape=(300153, 4))

In [94]:
x_train,xtest,ytrain,ytest = train_test_split(X_selected,y,test_size=0.2,random_state=42)
rf.fit(x_train,ytrain)
print(rf.score(xtest,ytest))

0.9336330447835891

In [103]:
# --------------------------new_x---------------------

In [100]:
new_x = x[['source_city', 'class', 'duration', 'days_left','destination_city','flight','airline']]

In [101]:
new_x

,source_city,class,duration,days_left,destination_city,flight,airline
index,,,,,,,
0,2,1,2.17,1,5,4,4
1,2,1,2.33,1,5,4,4
2,2,1,2.17,1,5,3,0
3,2,1,2.25,1,5,5,5
4,2,1,2.33,1,5,5,5
...,...,...,...,...,...,...,...
300148,1,0,10.08,49,3,5,5
300149,1,0,10.42,49,3,5,5
300150,1,0,13.83,49,3,5,5
300151,1,0,10.00,49,3,5,5
300152,1,0,10.08,49,3,5,5

In [99]:
y

index
0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [102]:
x_train,xtest,ytrain,ytest = train_test_split(new_x,y,test_size=0.2,random_state=42)
rf.fit(x_train,ytrain)
print(rf.score(xtest,ytest))

0.9784275720695403

# Data_Transformation

In [19]:
from sklearn.pipeline import Pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [20]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
numeric_columns = xtrain.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_columns = xtrain.select_dtypes(include=['object']).columns.tolist()

num_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore')),
    ('scaler', StandardScaler(with_mean=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_pipeline, numeric_columns),
    ('cat', cat_pipeline, categorical_columns)
])

In [22]:
xtrain_arr = preprocessor.fit_transform(xtrain)
xtest_arr = preprocessor.transform(xtest)

### Model_Trainier

In [23]:
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import GridSearchCV

In [24]:
models = {
                "Random Forest": RandomForestRegressor(),
                "Decision Tree": DecisionTreeRegressor(),
                "Gradient Boosting": GradientBoostingRegressor(),
                "Linear Regression": LinearRegression(),
                "XGBRegressor": XGBRegressor(),
                "CatBoosting Regressor": CatBoostRegressor(verbose=False),
                "AdaBoost Regressor": AdaBoostRegressor(),
            }

In [ ]:
params = {
                "Decision Tree": {
                    # 'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
                    # 'splitter': ['best', 'random'],
                    # 'max_depth': [3, 5, 10, None],
                    # 'min_samples_split': [2, 5, 10],
                    # 'min_samples_leaf': [1, 2, 5],
                    #'max_features': ['sqrt', 'log2', None]
                },
                "Random Forest": {
                    #'n_estimators': [50, 100, 200, 300],
                    # 'criterion': ['squared_error', 'friedman_mse'],
                    # 'max_depth': [5, 10, None],
                    # 'max_features': ['sqrt', 'log2', None],
                    # 'min_samples_split': [2, 5, 10],
                    # 'min_samples_leaf': [1, 2, 4]
                },
                "Gradient Boosting": {
                    #'n_estimators': [100, 200, 300],
                    #'learning_rate': [0.1, 0.05, 0.01],
                    # 'subsample': [0.6, 0.8, 1.0],
                    # 'max_depth': [3, 5, 7],
                    # 'min_samples_split': [2, 5, 10],
                    # 'min_samples_leaf': [1, 2, 5]
                },
                "Linear Regression": {
                    'fit_intercept': [True, False]
                },

                "XGBRegressor": {
                    #'n_estimators': [100, 200, 300],
                    #'learning_rate': [0.1, 0.05, 0.01],
                    # 'max_depth': [3, 5, 7],
                    # 'subsample': [0.6, 0.8, 1.0],
                    # 'colsample_bytree': [0.6, 0.8, 1.0],
                    # 'gamma': [0, 1, 5]
                },
                "CatBoosting Regressor": {
                    #'iterations': [100, 200, 300],
                    # 'depth': [6, 8, 10],
                    # 'learning_rate': [0.1, 0.05, 0.01],
                    # 'l2_leaf_reg': [1, 3, 5, 7]
                },
                "AdaBoost Regressor": {
                    #'n_estimators': [50, 100, 200],
                    # 'learning_rate': [0.1, 0.5, 1.0],
                    # 'loss': ['linear', 'square', 'exponential']
                }
            }

In [26]:
for model_name,model in models.items():
    param = params[model_name]

    gs = GridSearchCV(model,param,cv=3)
    gs.fit(xtrain,ytrain)

    best_params = gs.best_params_
    model.set_params(**best_params)
    model.fit(xtrain,ytrain)

    ypred_train = model.predict(xtrain)
    ypred_test = model.predict(xtest)

    train_score = r2_score(ytrain,ypred_train)
    test_score = r2_score(ytest,ypred_test)

In [27]:
test_score

0.9257414058150116

In [30]:
train_score

0.9267788293099983

In [28]:
best_params

{'n_estimators': 200}

In [29]:
model

AdaBoostRegressor(n_estimators=200)

In [31]:
param

{'n_estimators': [50, 100, 200]}